version: '3.4'

x-common-config: &common_config
  image: foundriesio/conductor:1.7.0
  build:
    context: .
  volumes:
    - home:/app
    - ${EXTRA_SETTINGS_PATH}:/home/
  environment:
    - CONDUCTOR_CELERY_BROKER_URL="amqp://conductor:secret@172.17.0.1/conductor"
    - CONDUCTOR_EXTRA_SETTINGS=/home/extra_settings.py
    - LOGLEVEL=INFO
    - USRNAME=conductor
    - GROUPNAME=conductor

volumes:
  home:

services:
  dbmigrate:
    <<: *common_config
    command: conductor-admin migrate
    deploy:
      restart_policy:
        condition: none

  web:
    <<: *common_config
    command: /usr/bin/gunicorn conductor.wsgi --log-level ${LOGLEVEL} --bind 0.0.0.0:8000
    ports:
      - '9000:8000'
    depends_on:
      - dbmigrate

  tmp:
    <<: *common_config
    command: echo ${USRNAME}

  worker:
    <<: *common_config
    command: conductor-worker
    depends_on:
      - dbmigrate

  listener:
    <<: *common_config
    command: conductor-listener -v 2
    depends_on:
      - dbmigrate

