# Copyright 2022 Foundries.io
#
# SPDX-License-Identifier: BSD-3-Clause

# Generated by Django 4.0.4 on 2022-10-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0003_testjob_is_el2go_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdefinition',
            name='branch',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
