# Generated by Django 4.0.4 on 2022-10-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0004_testdefinition_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestJobTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='testjob',
            name='tags',
            field=models.ManyToManyField(null=True, to='testplan.testjobtag'),
        ),
    ]
