# Generated by Django 4.0.4 on 2023-08-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0006_alter_testaction_name_alter_testjob_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjob',
            name='is_static_delta_job',
            field=models.BooleanField(default=False),
        ),
    ]
