# Copyright 2023 Foundries.io
#
# SPDX-License-Identifier: BSD-3-Clause

# Generated by Django 4.0.4 on 2023-10-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0007_testjob_is_static_delta_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjob',
            name='is_downgrade_job',
            field=models.BooleanField(default=False),
        ),
    ]
