# Generated by Django 4.0.4 on 2024-01-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0008_testjob_is_downgrade_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjob',
            name='is_assemble_image_job',
            field=models.BooleanField(default=False),
        ),
    ]
