# Generated by Django 4.0.4 on 2024-06-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0009_testjob_is_assemble_image_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boot',
            name='prompts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
