# Generated by Django 4.2.13 on 2024-09-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0012_alter_testjob_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boot',
            name='method',
            field=models.CharField(choices=[('minimal', 'minimal'), ('qemu', 'qemu')], max_length=32),
        ),
    ]
