# Generated by Django 4.2.13 on 2024-10-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0013_alter_boot_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavaaction',
            name='docker_image',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
