# Generated by Django 4.2.13 on 2025-04-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testplan", "0014_lavaaction_docker_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="failure_retry",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
