# Copyright 2021 Foundries.io
#
# SPDX-License-Identifier: BSD-3-Clause

# Generated by Django 3.1.7 on 2021-03-17 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDUAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('state', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=16)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='lavadevice',
            name='controlled_by',
            field=models.CharField(choices=[('LAVA', 'Lava'), ('PDU', 'PDU')], default='LAVA', max_length=16),
        ),
        migrations.AddField(
            model_name='lavadevice',
            name='pduagent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pduagent'),
        ),
    ]
