# Copyright 2021 Foundries.io
#
# SPDX-License-Identifier: BSD-3-Clause

# Generated by Django 3.1.7 on 2021-03-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210317_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='pduagent',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
