# Generated by Django 3.1.7 on 2021-04-14 12:39
#
# SPDX-License-Identifier: BSD-3-Clause

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lavadevicetype_device_type_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='commit_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='is_release',
            field=models.BooleanField(default=False),
        ),
    ]
