# Generated by Django 3.1.7 on 2021-04-15 10:27
#
# SPDX-License-Identifier: BSD-3-Clause

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_websocket_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavajob',
            name='job_type',
            field=models.CharField(choices=[('LAVA', 'Lava'), ('OTA', 'OTA')], default='LAVA', max_length=16),
        ),
    ]
