# Generated by Django 3.1.7 on 2021-04-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lavajob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavadevice',
            name='ota_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
