# Generated by Django 3.1.7 on 2021-04-28 13:20
#
# SPDX-License-Identifier: BSD-3-Clause

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lavadevice_auto_register_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavadevicetype',
            name='ota_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
