# Generated by Django 3.1.7 on 2021-05-18 12:15
#
# SPDX-License-Identifier: BSD-3-Clause

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lavadevicetype_ota_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAVABackend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('lava_url', models.URLField()),
                ('websocket_url', models.URLField(blank=True, null=True)),
                ('lava_api_token', models.CharField(max_length=128)),
            ],
        ),
    ]
