# Generated by Django 3.1.7 on 2021-10-29 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_build_reason_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQUADBackend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('squad_url', models.URLField()),
                ('squad_token', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='squad_group',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='squad_backend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.squadbackend'),
        ),
    ]
