# Copyright 2022 Foundries.io
#
# SPDX-License-Identifier: BSD-3-Clause

# Generated by Django 3.1.7 on 2022-02-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_buildtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='privkey',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
