# Generated by Django 3.1.7 on 2022-03-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_project_privkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='privkey',
            field=models.TextField(blank=True, null=True),
        ),
    ]
