# Generated by Django 3.1.7 on 2022-03-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_privkey_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='keyid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
