# Copyright 2022 Foundries.io
#
# SPDX-License-Identifier: BSD-3-Clause

# Generated by Django 3.1.7 on 2022-03-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_project_keyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_branch',
            field=models.CharField(default='master', max_length=16),
        ),
    ]
