# Copyright 2022 Foundries.io
#
# SPDX-License-Identifier: BSD-3-Clause

# Generated by Django 3.1.7 on 2022-07-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_project_default_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='create_ota_commit',
            field=models.BooleanField(default=False),
        ),
    ]
