# Generated by Django 4.0.4 on 2022-09-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0001_initial'),
        ('core', '0025_project_fio_repository_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='testplans',
            field=models.ManyToManyField(null=True, to='testplan.testplan'),
        ),
    ]
