# Copyright 2022 Foundries.io
#
# SPDX-License-Identifier: BSD-3-Clause

# Generated by Django 4.0.4 on 2022-09-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0002_alter_testjob_name'),
        ('core', '0026_project_testplans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='testplans',
            field=models.ManyToManyField(blank=True, null=True, to='testplan.testplan'),
        ),
    ]
