# Generated by Django 4.0.4 on 2022-09-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_project_testplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='qa_reports_project_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
