# Generated by Django 4.0.4 on 2022-09-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_project_qa_reports_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavadevice',
            name='el2go_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='el2go_product_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='lavadevice',
            name='controlled_by',
            field=models.CharField(choices=[('LAVA', 'Lava'), ('PDU', 'PDU'), ('EL2G', 'EL2GO')], default='LAVA', max_length=16),
        ),
    ]
