# Copyright 2022 Foundries.io
#
# SPDX-License-Identifier: BSD-3-Clause

# Generated by Django 4.0.4 on 2022-10-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_lavadevice_el2go_name_project_el2go_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='lmp_commit',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='lavajob',
            name='job_type',
            field=models.CharField(choices=[('LAVA', 'Lava'), ('OTA', 'OTA'), ('EL2GO', 'EL2GO')], default='LAVA', max_length=16),
        ),
    ]
