# Generated by Django 4.0.4 on 2022-10-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0006_alter_testaction_name_alter_testjob_tags'),
        ('core', '0030_build_lmp_commit_alter_lavajob_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='testplans',
            field=models.ManyToManyField(blank=True, to='testplan.testplan'),
        ),
    ]
