# Generated by Django 4.0.4 on 2023-01-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_project_testplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='is_merge_commit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='test_on_merge_only',
            field=models.BooleanField(default=False),
        ),
    ]
