# Copyright 2023 Foundries.io
#
# SPDX-License-Identifier: BSD-3-Clause

# Generated by Django 4.0.4 on 2023-02-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_build_is_merge_commit_project_test_on_merge_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='compose_app_env_filename',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='compose_app_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='create_containers_commit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='default_container_branch',
            field=models.CharField(default='master', max_length=64),
        ),
    ]
