# Copyright 2023 Foundries.io
#
# SPDX-License-Identifier: BSD-3-Clause

# Generated by Django 4.0.4 on 2023-06-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_project_compose_app_env_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='skip_qa',
            field=models.BooleanField(default=False),
        ),
    ]
