# Copyright 2023 Foundries.io
#
# SPDX-License-Identifier: BSD-3-Clause

# Generated by Django 4.0.4 on 2023-06-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_build_skip_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='apply_tag_to_first_build_only',
            field=models.BooleanField(default=False),
        ),
    ]
