# Copyright 2023 Foundries.io
#
# SPDX-License-Identifier: BSD-3-Clause

# Generated by Django 4.0.4 on 2023-06-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_project_apply_tag_to_first_build_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_meta_branch',
            field=models.CharField(default='master', max_length=64),
        ),
    ]
