# Generated by Django 4.0.4 on 2023-06-14 11:00

from django.db import migrations
from conductor.core.models import Project
from conductor.core.tasks import create_project_meta_repository


def initialize_meta_repositories(apps, schema_editor):
    for project in Project.objects.all():
        create_project_meta_repository(project.pk)


def remove_repositories(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_project_default_meta_branch'),
    ]

    operations = [
        migrations.RunPython(initialize_meta_repositories, remove_repositories),
    ]
