# Copyright 2023 Foundries.io
#
# SPDX-License-Identifier: BSD-3-Clause

# Generated by Django 4.0.4 on 2023-07-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_project_lava_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='build_trigger',
            field=models.CharField(choices=[('LMP', 'LmP Manifest'), ('MET', 'Meta Subscriber Overrides')], default='LMP', max_length=3),
        ),
    ]
