# Generated by Django 4.0.4 on 2023-08-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_build_restart_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='build_type',
            field=models.CharField(choices=[('REG', 'Ordinary build (manifest or meta-sub)'), ('OTA', 'OTA build'), ('SDE', 'Create static delta between targets')], default='REG', max_length=3),
        ),
    ]
