# Copyright 2023 Foundries.io
#
# SPDX-License-Identifier: BSD-3-Clause

# Generated by Django 4.0.4 on 2023-08-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_build_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='schedule_tests',
        ),
    ]
