# Generated by Django 4.0.4 on 2023-09-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_build_static_from_build_static_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='build_status',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
