# Generated by Django 4.0.4 on 2023-10-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_build_build_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fio_lmp_manifest_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
