# Copyright 2023 Foundries.io
#
# SPDX-License-Identifier: BSD-3-Clause

# Generated by Django 4.0.4 on 2023-11-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_build_build_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavadevicetype',
            name='architecture',
            field=models.CharField(choices=[('armhf', 'armhf'), ('arm64', 'arm64'), ('amd64', 'amd64')], default='arm64', max_length=8),
        ),
    ]
