# Generated by Django 4.0.4 on 2024-01-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_update_lava_device_architecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavadevicetype',
            name='architecture',
            field=models.CharField(choices=[('armhf', 'armhf'), ('arm64', 'arm64'), ('aarch64', 'aarch64'), ('amd64', 'amd64')], default='aarch64', max_length=8),
        ),
    ]
