# Copyright 2024 Foundries.io
#
# SPDX-License-Identifier: BSD-3-Clause

# Generated by Django 4.0.4 on 2024-02-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_lavajob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavajob',
            name='status',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
