# Generated by Django 4.0.4 on 2024-03-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_lavajob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='build_type',
            field=models.CharField(choices=[('REG', 'Ordinary build (manifest or meta-sub)'), ('OTA', 'OTA build'), ('SDE', 'Create static delta between targets'), ('CTR', 'Containers build'), ('GPR', 'Code Review')], default='REG', max_length=3),
        ),
    ]
