# Generated by Django 4.2.13 on 2024-07-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_project_fioctl_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='ostree_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
