# Generated by Django 4.2.13 on 2024-08-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_run_ostree_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='forked_from',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
