# Generated by Django 4.2.13 on 2024-09-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_project_default_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
