# Generated by Django 4.2.13 on 2024-09-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_project_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='disabled',
            field=models.BooleanField(default=False, help_text='When set to True, automatic merges are switched off. It is still possible to manually trigger test rounds.'),
        ),
    ]
