# Generated by Django 4.2.13 on 2024-10-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_delete_pduagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='restart_failed_builds',
            field=models.BooleanField(default=True, help_text='Restart failed CI builds'),
        ),
    ]
