# Generated by Django 4.2.13 on 2024-10-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_project_restart_failed_builds'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lavadevicetype',
            unique_together={('name', 'project')},
        ),
    ]
