# Generated by Django 4.2.13 on 2024-11-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_alter_lavadevicetype_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lavajob",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.project",
            ),
        ),
    ]
