# Generated by Django 4.2.13 on 2025-03-31 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_alter_lavajob_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="lavajob",
            name="requested_device_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.lavadevicetype",
            ),
        ),
    ]
