# Generated by Django 4.2.13 on 2025-03-31 13:21

from django.db import migrations

def fill_lavajob_requested_device_type(apps, schema_editor):
    LAVAJob = apps.get_model('core', 'LAVAJob')
    for job in LAVAJob.objects.all():
        if job.device is not None:
            job.requested_device_type = job.device.device_type
            job.save()

def revert_lavajob_requested_device_type(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_lavajob_requested_device_type"),
    ]

    operations = [
        migrations.RunPython(fill_lavajob_requested_device_type, revert_lavajob_requested_device_type),
    ]
